<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNywy59j\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNywy59j/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerNywy59j.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerNywy59j\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerNywy59j\appProdProjectContainer([
    'container.build_hash' => 'Nywy59j',
    'container.build_id' => 'a6124dfe',
    'container.build_time' => 1689761756,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNywy59j');
